import type { Conversation, Message, ContentBlock } from "@runyard/common";
declare class ChatStore {
    conversations: Conversation[];
    activeConversationId: string | null;
    messages: Message[];
    isStreaming: boolean;
    conversationTabs: string[];
    activeTabId: string | null;
    searchQuery: string;
    workspaceFilter: string | null;
    sortBy: "name" | "recent" | "tokens";
    branches: Branch[];
    pinnedContext: PinnedContext[];
    filteredConversations: Conversation[];
    constructor();
    init(): Promise<void>;
    selectConversation(id: string): Promise<void>;
    loadMessages(conversationId: string, page?: number, limit?: number): Promise<void>;
    createConversation(title: string, model: string, workspacePath?: string, provider?: string, systemPrompt?: string, contextBudget?: number): Promise<string>;
    updateConversation(id: string, updates: Partial<Omit<Conversation, "id" | "created_at" | "updated_at">>): Promise<void>;
    renameConversation(id: string, newTitle: string): Promise<void>;
    moveConversation(id: string, newWorkspacePath: string): Promise<void>;
    deleteConversation(id: string): Promise<void>;
    openConversationInTab(id: string): void;
    closeConversationTab(id: string): Promise<void>;
    sendMessage(content: ContentBlock[]): Promise<void>;
    updateMessage(id: string, content: ContentBlock[]): Promise<void>;
    setMessagePinned(id: string, isPinned: boolean): Promise<void>;
    searchMessages(query: string): Promise<Message[]>;
    loadPinnedContext(conversationId: string): Promise<void>;
    pinFile(filePath: string): Promise<void>;
    unpinFile(id: string): Promise<void>;
    loadBranches(conversationId: string): Promise<void>;
    createBranch(name: string, messageId: string): Promise<void>;
    deleteBranch(id: string): Promise<void>;
}
export declare const chatStore: ChatStore;
export {};
